<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    //General
    'Id' => 'ID',
    'Type' => 'Тип',
    'Submit' => 'Отправить',
    'Name' => 'Имя',
    'Browse' => 'Выбрать',
    'Content' => 'Содержание',
    'Created At' => 'Дата создания',
    'Clear Filters' => 'Сбросить фильтры',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Update' => 'Изменить',
    'Login' => 'Логин',
    'Save' => 'Сохранить',
    'Save And Create New' => 'Сохранить и добавить еще',
    'Save And Return To List' => 'Сохранить и вернуться к списку',
    'Search' => 'Найти',
    'Search...' => 'Найти...',
    'Search section...' => 'Найти раздел...',
    'Settings' => 'Настройки',
    'Range' => 'Диапазон',
    'Waiting for results...' => 'Ожидание результатов...',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить элемент?',

    'User IP' => 'IP Пользователя',
    'Email Subject' => 'Заголовок письма',
    'Email Template' => 'Шаблон письма',

    //PARAMS
    'Params' => 'Параметры',
    'Create Param' => 'Добавить параметр',
    'New Param' => 'Новый параметр',
    'Group' => 'Группа',
    'Is Active' => 'Доступен на сайте',

    'Auth source' => 'Способ авторизации',
    'Access Token' => 'Токен доступа',
    'Auth Key' => 'Ключ авторизации',
    'Backup DB' => 'Резервное копирование БД',
    'Blocked At' => 'Дата блокировки',
    'Create Text' => 'Добавить текст',
    'Create User Admin' => 'Добавить Администратора',
    'Display Name' => 'Отображаемое имя',
    'E-mail' => 'E-mail',
    'Email' => 'E-mail',
    'Email Settings' => 'Настройки почты',
    'Emails' => 'Рассылки',
    'Ended At' => 'Дата и время окончания',
    'Export DB' => 'Экспортировать БД',
    'Export Images' => 'Экспортировать изображения',
    'Feedback Subjects' => 'Темы обратной связи',
    'Feedbacks' => 'Обратная связь',
    'First' => 'Первая',
    'File Manager' => 'Файловый менеджер',
    'Images' => 'Изображения',
    'Files' => 'Файлы',
    'Video' => 'Видео',
    'Audio' => 'Аудио',
    'Flags' => 'Флаги',
    'Is Shared' => 'Расшарено',
    'Last' => 'Последняя',
    'Last Auth Date' => 'Дата последней авторизации',
    'Last Login At' => 'Дата последней авторизации',
    'Last Run' => 'Последний запуск',
    'Last IP' => 'Последний IP',
    'Linked {client} account.' => 'Связанный аккаунт',
    'Messages' => 'Сообщения',
    'Next Run' => 'Следующий запуск',
    'Overview' => 'Обзор',
    'Output' => 'Вывод',
    'Only words and numbers allowed, use "_" instead of spaces' => 'Разрешены только буквы и цифры, вместо пробелов использовать "_"',
    'Password must consist of at least 6 characters' => 'Пароль должен содержать минимум 6 символов',
    'Partners' => 'Партнёры',
    'Parameter' => 'Параметр',
    'Phone' => 'Телефон',
    'Posts' => 'Посты',
    'Priority' => 'Приоритет',
    'Registration Ip' => 'IP регистрации',
    'Reset' => 'Сбросить',
    'Started At' => 'Дата и время начала',
    'Status' => 'Статус',
    'Status ID' => 'ID статуса',
    'Subject ID' => 'Тема',
    'Test Groups' => 'Группы текстов',
    'Text' => 'Текст',
    'Texts' => 'Тексты',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Title' => 'Название',
    'This username has already been taken.' => 'Этот логин уже занят',
    'This email address has already been taken.' => 'Эта почта уже занята',
    'Unable to link {client} account. There is another user using it.' => 'Не удалось связаться с аккаунтом. В данный момент он используется другим пользователем',
    'Unable to link {client} account: {errors}' => 'Не удалось связаться с аккаунтом. {errors}',
    'Unable to save user: {errors}' => 'Не удалось сохранить пользователя: {errors}',
    'Unable to save {client} account: {errors}' => 'Не удалось сохранить клиент: {errors}',
    'Unconfirmed Email' => 'Неподтверждённый E-mail',
    'Update Text: {name}' => 'Изменить текст: {name}',
    'Updated At' => 'Дата изменения',
    'User Admins' => 'Администраторы',
    'User ID' => 'Пользователь',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => 'Пользователь с такой электронной почтой как в {client} уже существует, но с ним не связан. Для начала войдите на сайт использую электронную почту, для того, что бы связать её.',
    'Username' => 'Имя пользователя',
    'First Name' => 'Имя',
    'New Text' => 'Новый текст',
    'New User Admin' => 'Новый администратор',
    'Middle Name' => 'Отчество',
    'Last Name' => 'Фамилия',
    'Users' => 'Пользователи',
    'Value' => 'Значение',
    'Verified' => 'Подтверждён',
    'Testing' => 'Тестирование',
    'Auth Source' => 'Источник регистрации',
    'Email is confirmed' => 'Email подтвержден',
    'Email is not confirmed' => 'Email не подтвержден',
    'Email Verified At' => 'Дата подтверждения Email',
    'Key' => 'Ключ',
    'Email Logs' => 'Логи отправки email',
    'Template' => 'Шаблон',
    'Subject' => 'Тема',
    'Data' => 'Данные',
    'Send Status' => 'Статус отправки',
    'Send At' => 'Отправлено',
    'Inited From' => 'Инициатор',

    'Update User Admin: ' => 'Изменить пользователя: ',
    'Is Password Reset Blocked' => 'Сброс пароля заблокирован',

    // Sortable Grid View
    'Loading...' => 'Загрузка...',
    'Fail to sort' => 'Ошибка сортировки',

    // UserAdmin
    'Update User Admin: {name}' => 'Изменить администратора: {name}',
    'Password' => 'Пароль',
    'New Password' => 'Новый пароль',
    'Repeat Password' => 'Повторите пароль',
    'Current Password' => 'Текущий пароль',
    'Wrong Current Password' => 'Неправильный текущий пароль',
    'Password Change' => 'Смена пароля',
    'Password Reset Token' => 'Токен сброса пароля',
    'Password Hash' => 'Хэш пароля',

    //Statistics
    'Statistics' => 'Статистика',
    'The number of users who are fully registered' => 'Число пользователей, которые полностью прошли регистрацию',

    //Site Export
    'Site Export' => 'Экспорт сайта',
    'Export' => 'Экспортировать',
    'Export Lists' => 'Список экспорта',
    'Download Link' => 'Ссылка на скачивание',
    'Count' => 'Кол-во',
    'Date' => 'Дата',
];
